version: 0.0.6.{build}

image:
    - Visual Studio 2017

platform:
    - x64

branches:
    only:
        - master

clone_depth: 5

configuration:
    - Release
    - Debug

before_build:
    - mkdir build
    - cd build
    - dir
    - cmake --version
    - cmake .. -DGTEST_HAS_TR1_TUPLE=0 -G "Visual Studio 15 2017 Win64"

build:
    project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln
    verbosity: minimal
    parallel: true

test_script:
    - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\build\unit_tests_with_googletest.exe'
